name: Makefile CI

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: make defconfig
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make all
