name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker
        uses: docker/setup-docker-action@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build --platform linux/arm64 -t myimage .
          docker run --rm myimage echo "Build successful!"


